### ISSUE TITLE
`fatal error: opencv2/opencv.hpp: No such file or directory` encountered while attempting to build unit tests

### ISSUE THREAD

**Issue by capsulecorplab** [fprime-community/fprime-system-reference#50]
encountered following error after generating stubs with `fprime-util generate --ut` then attempting to run build with `fprime-util build --ut` as of https://github.com/fprime-community/fprime-system-reference/commit/a49e3179ea0eea972028d650cffa3f22602d77b6

![Screenshot from 2023-07-14 12-46-46](https://github.com/fprime-community/fprime-system-reference/assets/14095576/212394b5-9881-4546-83dd-3bdd1ad498c6)

**Comment by jwest115** [comment]
We have replaced OpenCV with libcamera, so this issue should no longer be needed, closing.
